# Generated by Django 4.2.2 on 2023-06-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theplanner', '0002_rename_post_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='body',
            new_name='task',
        ),
    ]
