# Generated by Django 4.2.2 on 2023-06-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theplanner', '0003_rename_title_task_category_rename_body_task_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
