# Generated by Django 4.2.2 on 2023-06-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theplanner', '0005_category_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('task', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
