# Generated by Django 4.2.2 on 2023-06-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theplanner', '0007_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourTimer', models.IntegerField(max_length=2)),
                ('minuteTimer', models.IntegerField(max_length=2)),
            ],
        ),
    ]
