# Generated by Django 4.2.2 on 2023-06-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theplanner', '0008_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hourTimer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='minuteTimer',
            field=models.IntegerField(),
        ),
    ]
