# Generated by Django 4.2.2 on 2023-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theplanner', '0009_alter_session_hourtimer_alter_session_minutetimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.IntegerField()),
            ],
        ),
    ]
