# Generated by Django 4.2.2 on 2023-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theplanner', '0012_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='task',
        ),
        migrations.AddField(
            model_name='home',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
