# Generated by Django 4.2.2 on 2023-12-04 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theplanner', '0013_remove_home_task_home_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AlterField(
            model_name='home',
            name='activity',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='home',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
